CNN-Image classify

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np
import cv2
import os
from tqdm import tqdm
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import random
import tensorflow

In [ ]:
from os import listdir
from os.path import isfile, join

In [ ]:
from matplotlib.pyplot import imshow
import matplotlib.cm as cm
import matplotlib.pylab as plt
from keras.preprocessing.image import ImageDataGenerator
import numpy as np
import PIL
from PIL import ImageFilter
import cv2
import itertools
import random
import keras
import imutils
from imutils import paths
import os
from keras import optimizers
from keras.preprocessing.image import img_to_array
from sklearn.model_selection import train_test_split
# from keras.utils import to_categorical
from keras import callbacks
from keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D , UpSampling2D ,Conv2DTranspose
from keras import backend as K

%matplotlib inline

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Reshape, Flatten

import random
import os

In [ ]:
width = 64
num_classes = 10
trainpath = '/content/data/font_fam/'
testpath = '/content/data/font_fam/'
print(listdir(trainpath))
trainImg = [trainpath+f for f in listdir(trainpath) if listdir(join(trainpath, f))]
testImg = [testpath+f for f in listdir(testpath) if listdir(join(testpath, f))]

['Kunlasatri', 'TH_Mali_Grade6', 'CORDIA', 'fonttintin', 'DM_Shining Star_Regular', 'FC_Knomphing_Regular', 'TH_Charm_of_AU', 'THSarabun', 'Angsana_New', 'TH_Chakra_Petch']


In [ ]:
# testImg

In [ ]:
from keras.preprocessing import image
import random
def img2dataTrainTest(path, trainsize=0.8, testsizze = 0.2):
  rawImgs = []
  labels = []
  x_train= [] 
  y_train= [] 
  x_test= [] 
  y_test = []
  c = 0
  samp = 0
  for imagePath in (path):

      for item in tqdm(os.listdir(imagePath)):
          file = os.path.join(imagePath, item)

          RAND = random.random()
          if(RAND < trainsize):
            l = (item.split("_")[-2] + "-" + item.split("_")[-1]).split(".")[0]
            # print(l)
            if(l[-1] ==")"):
              print("continue")
              continue
            if l == 'normal-bold':
              y_train.append([1,0,0,0])         
            if l == 'italic-bold':  # most
              y_train.append([0,1,0,0])
            if l == 'normal-normal': # 0
              y_train.append([0,0,1,0])
            if l == 'italic-normal':
              y_train.append([0,0,0,1])
            # else:
            #   print("notmatch")
            #   print(item)

            img = image.load_img(file, grayscale=True)
            img = img.crop((0,0,112,28))

            ## Convert the Image object into a numpy array
            img = image.img_to_array(img)

            ## Add to a list of images and classes
            x_train.append(img)
          else:
            l = (item.split("_")[-2] + "-" + item.split("_")[-1]).split(".")[0]
            # print(l)
            if(l[-1] ==")"):
              print("continue")
              continue             
            if l == 'normal-bold':
              # print("xxxxxx")
              y_test.append([1,0,0,0])         
            if l == 'italic-bold':  # most
              y_test.append([0,1,0,0])
            if l == 'normal-normal': # 0
              y_test.append([0,0,1,0])
            if l == 'italic-normal':
              y_test.append([0,0,0,1])
            # else:
            #   print("notmatch")
              # print(item)

            img = image.load_img(file, grayscale=True)
            img = img.crop((0,0,112,28))

            ## Convert the Image object into a numpy array
            img = image.img_to_array(img)

            ## Add to a list of images and classes
            x_test.append(img)

            
  return x_train, y_train, x_test, y_test

In [ ]:
x_train, y_train, x_test, y_test = img2dataTrainTest(trainImg)

  0%|          | 0/6883 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
  9%|▉         | 683/7294 [00:00<00:01, 3421.84it/s]

continue
continue


 19%|█▊        | 1365/7294 [00:00<00:01, 3254.13it/s]

continue
continue
continue


 37%|███▋      | 2708/7294 [00:00<00:01, 3245.74it/s]

continue
continue
continue
continue


 46%|████▌     | 3370/7294 [00:01<00:01, 3258.61it/s]

continue
continue
continue
continue


 55%|█████▌    | 4040/7294 [00:01<00:00, 3308.86it/s]

continue


 69%|██████▉   | 5038/7294 [00:01<00:00, 3254.02it/s]

continue
continue
continue


 88%|████████▊ | 6387/7294 [00:01<00:00, 3341.36it/s]

continue


100%|██████████| 7294/7294 [00:02<00:00, 3300.29it/s]


continue


100%|██████████| 7223/7223 [00:02<00:00, 3053.62it/s]


In [ ]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [ ]:
x_train.shape,y_train.shape,x_test.shape, y_test.shape

((52501, 28, 112, 1), (52501, 4), (13015, 28, 112, 1), (13015, 4))

In [ ]:
y_test

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       ...,
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [ ]:
epochs = 20
batch_size = 128

In [ ]:
model=Sequential()

#model.add(Lambda(standardize,input_shape=(28,28,1)))    
model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu", input_shape=(28,112,1)))
model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu"))

model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))
model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))

model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())    
model.add(Conv2D(filters=256, kernel_size = (3,3), activation="relu"))
model.add(Dropout(0.25))
    
model.add(MaxPooling2D(pool_size=(2,2)))
    
model.add(Flatten())
model.add(BatchNormalization())
model.add(Dense(512,activation="relu"))
model.add(Dropout(0.25))

model.add(Dense(4,activation="softmax"))
    
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
model=Sequential()

#model.add(Lambda(standardize,input_shape=(28,28,1)))    
model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu", input_shape=(28,112,1)))
model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu"))

model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))
model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))

model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())    
model.add(Conv2D(filters=256, kernel_size = (3,3), activation="relu"))
model.add(Dropout(0.5))
    
model.add(MaxPooling2D(pool_size=(2,2)))
    
model.add(Flatten())
model.add(BatchNormalization())
model.add(Dense(256,activation="relu"))
model.add(Dropout(0.5))

model.add(Dense(4,activation="softmax"))
    
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
directory = '/content/drive/MyDrive/Machima/MiniHackathon-Week1-FontRecogition/font_recognition/train/TrainsetPad/Weight-Style/'

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.4) # set validation split

train_generator = train_datagen.flow_from_directory(
    directory,
    color_mode='grayscale',
    target_size=(28, 112),
    batch_size=128,
    subset='training') # set as training data

print(directory)
validation_generator = train_datagen.flow_from_directory(
    directory, # same directory as training data
    target_size=(28, 112),
    color_mode='grayscale',
    batch_size=128,
    subset='validation') # set as validation data  

Found 15004 images belonging to 4 classes.
/content/drive/MyDrive/Machima/MiniHackathon-Week1-FontRecogition/font_recognition/train/TrainsetPad/Weight-Style/
Found 9999 images belonging to 4 classes.


In [ ]:
# With data augmentation to prevent overfitting

datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        #rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        rotation_range=0,
        zoom_range = 0.1, # Randomly zoom image 
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,  # randomly flip images
        vertical_flip=False)  # randomly flip images

datagen.fit(x_train)
#datagen.fit(X_train)
train_gen = datagen.flow(x_train, y_train, batch_size=batch_size)
val_gen = datagen.flow(x_test, y_test, batch_size=batch_size)

In [ ]:
early_stopping=callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='min')

filepath="/content/drive/MyDrive/Machi/Clear_Pong_style_weigth.h5"

checkpoint = callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')

callbacks_list = [early_stopping,checkpoint]

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.00001), loss='categorical_crossentropy'
                , metrics= ['accuracy'], weighted_metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_20 (Conv2D)          (None, 26, 110, 64)       640       
                                                                 
 conv2d_21 (Conv2D)          (None, 24, 108, 64)       36928     
                                                                 
 max_pooling2d_12 (MaxPoolin  (None, 12, 54, 64)       0         
 g2D)                                                            
                                                                 
 batch_normalization_12 (Bat  (None, 12, 54, 64)       256       
 chNormalization)                                                
                                                                 
 conv2d_22 (Conv2D)          (None, 10, 52, 128)       73856     
                                                                 
 conv2d_23 (Conv2D)          (None, 8, 50, 128)       

In [ ]:
# Fit the model
history = model.fit_generator(train_gen, 
                              epochs = epochs, 
                              
                              validation_data = val_gen,
                              callbacks=callbacks_list)

# poch 00011: val_loss improved from 0.11754 to 0.11280, saving model to /content/drive/MyDrive/Machi/Clear_Pong_style_weigth.h5
# 411/411 [==============================] - 58s 141ms/step - loss: 0.1164 - accuracy: 0.9497 - weighted_accuracy: 0.9497 - val_loss: 0.1128 - val_accuracy: 0.9514 - val_weighted_accuracy: 0.9514

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  


Epoch 1/20
411/411 [==============================] - ETA: 0s - loss: 0.1263 - accuracy: 0.9446 - weighted_accuracy: 0.9446
Epoch 00001: val_loss improved from 0.17997 to 0.13333, saving model to /content/drive/MyDrive/Machi/Clear_Pong_style_weigth.h5
411/411 [==============================] - 59s 141ms/step - loss: 0.1263 - accuracy: 0.9446 - weighted_accuracy: 0.9446 - val_loss: 0.1333 - val_accuracy: 0.9419 - val_weighted_accuracy: 0.9419
Epoch 2/20
411/411 [==============================] - ETA: 0s - loss: 0.1220 - accuracy: 0.9458 - weighted_accuracy: 0.9458
Epoch 00002: val_loss improved from 0.13333 to 0.11917, saving model to /content/drive/MyDrive/Machi/Clear_Pong_style_weigth.h5
411/411 [==============================] - 58s 141ms/step - loss: 0.1220 - accuracy: 0.9458 - weighted_accuracy: 0.9458 - val_loss: 0.1192 - val_accuracy: 0.9456 - val_weighted_accuracy: 0.9456
Epoch 3/20
411/411 [==============================] - ETA: 0s - loss: 0.1214 - accuracy: 0.9464 - weighted_a

#Prediction


In [ ]:
import pandas as pd
import os
from tqdm import tqdm
import cv2
import numpy as np

In [ ]:
testdir = '/content/test0/crop/'

In [ ]:
print(len(os.listdir(testdir)))

47746


In [ ]:
AllparentId = []
AllPredicted = []

In [ ]:
from tensorflow import keras
from keras.preprocessing import image
model = keras.models.load_model('/content/drive/MyDrive/Machi/AppMan/Clear_Pong_style_weigth.h5')

In [ ]:
def predict(path):
  predictions = []
  parentId = []
  for item in tqdm(os.listdir(path)[0:10]):

    img = image.load_img(testdir + item, grayscale=True)
    img = img.crop((0,0,112,28))

    ## Convert the Image object into a numpy array
    img = image.img_to_array(img)

    ## Add to a list of images and classes
    # x_test.append(img)

    # img = cv2.imread(testdir + item)
    # img = cv2.resize(img ,(105,105))
    
    # testimg = np.array(img)
    testimg = img.astype('float32')
    testimg /= 255
    rimg = np.reshape(testimg ,(1,28,112,1))
    predict = model.predict(rimg)
    label = ['normal-bold', 'italic-bold', 'normal-normal', 'italic-normal']
    # predict = model.predict(testimg)
    result = label[np.argmax(predict)]
    predictions.append(result)
    parentId.append(item.split(".")[0]+"_style-weight")
    # print(result)
            
  return parentId, predictions

In [ ]:
parentId, pred = predict(testdir)

  0%|          | 0/10 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
100%|██████████| 10/10 [00:00<00:00, 16.48it/s]


In [ ]:
pred

['normal-normal',
 'italic-normal',
 'normal-normal',
 'normal-normal',
 'normal-normal',
 'italic-normal',
 'normal-normal',
 'italic-normal',
 'italic-normal',
 'normal-normal']

In [ ]:
for i in tqdm(range(len(parentId))):
    idx = origin_submit['Id'].loc[lambda x: x==str(parentId[i])].index
    # print(idx[0])
    origin_submit['Predicted'][idx[0]] = pred[i]

  0%|          | 0/10 [00:00<?, ?it/s]


NameError: ignored

In [ ]:
origin_submit.to_csv('/content/drive/MyDrive/Machi/testSubmit.csv',index=False)

In [ ]:
df = pd.DataFrame(list(zip(parentId, pred)),
               columns =['Id', 'Predicted'])

In [ ]:
df.to_csv('/content/drive/MyDrive/Machi/Clear_weight-style_pong.csv',index=False)

#Merge df


In [ ]:
base_submission = pd.read_csv("/content/true_submition2.csv")
base_submission.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Id            Predicted
0          b68ab614_name      TH_Chakra_Petch
1          b68ab614_file  TH Chakra Petch.ttf
2          b68ab614_size                 24px
3  b68ab614_style-weight          italic-bold
4          2d3a3417_name      TH_Chakra_Petch

In [ ]:
new_submission = pd.read_csv("/content/drive/MyDrive/Machi/Clear_weight-style_pong.csv")
base_submission.head()

Id            Predicted
0          b68ab614_name      TH_Chakra_Petch
1          b68ab614_file  TH Chakra Petch.ttf
2          b68ab614_size                 24px
3  b68ab614_style-weight          italic-bold
4          2d3a3417_name      TH_Chakra_Petch

In [ ]:
for i in tqdm(range(len(new_submission['Id']))):
    idx = base_submission['Id'].loc[lambda x: x==str(new_submission['Id'][i])].index
#     print(idx[0])
    base_submission['Predicted'][idx[0]] = new_submission['Predicted'][i]

100%|██████████| 48251/48251 [19:55<00:00, 40.37it/s]


In [ ]:
base_submission.to_csv('Clear_Machi2_New_base_submission.csv',index=False)

#predict individual file


In [ ]:
def predictSome(path):
    c = 0
  
    predictions = []
    parentId = []
    c+=1
    img = image.load_img(path, grayscale=True)
    img = img.crop((0,0,112,28))

    ## Convert the Image object into a numpy array
    img = image.img_to_array(img)

    ## Add to a list of images and classes
    # x_test.append(img)

    # img = cv2.imread(testdir + item)
    # img = cv2.resize(img ,(105,105))
    
    # testimg = np.array(img)
    testimg = img.astype('float32')
    testimg /= 255
    rimg = np.reshape(testimg ,(1,28,112,1))
    predict = model.predict(rimg)
    label = ['normal-bold', 'italic-bold', 'normal-normal', 'italic-normal']
    result = label[np.argmax(predict)]
    predictions.append(result)
    parentId.append(path.split(".")[0])
    
    l = (path.split("_")[-2] + "-" + path.split("_")[-1]).split(".")[0]
    print(result)
    print(predict)
    print('real:'+str(l))
    print('predict:'+str(result))
    
            
    return parentId, predictions

In [ ]:
datapath = './data/font_fam/Angsana_New/'
datadir = './data/font_fam/'

In [ ]:
parentId, predictions = predictSome(datapath + os.listdir(datapath)[456])

/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


normal-normal
[[4.8719206e-01 1.0171854e-06 5.1280689e-01 6.5010248e-08]]
real:normal-bold
predict:normal-normal


In [ ]:
for path in(os.listdir(datadir)):
    print(">>>>>"+str(path)+"<<<<<")
    for i in range(5):
        print(datadir)
        a,b = predictSome(datadir+path+"/" + os.listdir(datadir+path)[i])
#         parentId, predictions = predictSome(datadir + os.listdir(datadir+path)[i])
        print("\n")

>>>>>Kunlasatri<<<<<
./data/font_fam/
italic-normal
[[0.0000000e+00 5.5063745e-29 8.3131566e-12 1.0000000e+00]]
real:italic-normal
predict:italic-normal


./data/font_fam/
normal-bold
[[9.9999368e-01 5.8550835e-08 6.2638510e-06 5.6775925e-16]]
real:normal-bold
predict:normal-bold


./data/font_fam/
normal-normal
[[1.4498589e-25 9.7407386e-31 9.9999988e-01 7.1780171e-08]]
real:normal-normal
predict:normal-normal


./data/font_fam/


/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/utils.py:107: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '


italic-bold
[[7.9841071e-16 9.9999988e-01 6.6775997e-21 1.1782207e-07]]
real:italic-bold
predict:italic-bold


./data/font_fam/
normal-bold
[[9.9233937e-01 5.0903665e-12 7.6606455e-03 5.6567223e-17]]
real:normal-bold
predict:normal-bold


>>>>>TH_Mali_Grade6<<<<<
./data/font_fam/
italic-bold
[[1.4550087e-12 9.9999511e-01 2.0845971e-16 4.9071255e-06]]
real:italic-bold
predict:italic-bold


./data/font_fam/
normal-bold
[[9.4382054e-01 5.4293178e-02 1.8355666e-03 5.0684688e-05]]
real:normal-bold
predict:normal-bold


./data/font_fam/
italic-bold
[[2.7202042e-08 9.1893333e-01 8.8968930e-09 8.1066661e-02]]
real:italic-bold
predict:italic-bold


./data/font_fam/
normal-normal
[[8.0223848e-11 1.8112944e-12 9.9359304e-01 6.4070141e-03]]
real:normal-normal
predict:normal-normal


./data/font_fam/
italic-normal
[[2.2009596e-37 3.4800478e-30 1.3848679e-06 9.9999857e-01]]
real:italic-normal
predict:italic-normal


>>>>>CORDIA<<<<<
./data/font_fam/
normal-normal
[[1.3262306e-06 7.1897703e-11 9.9991

#Predict-font-family-rule-base


In [ ]:
import pandas as pd
import os
from tqdm import tqdm
import cv2
import numpy as np

In [ ]:
origin_submit = pd.read_csv("/content/sample_submission.csv")
origin_submit.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Id            Predicted
0          b68ab614_name      TH_Chakra_Petch
1          b68ab614_file  TH Chakra Petch.ttf
2          b68ab614_size                 24px
3  b68ab614_style-weight          normal-bold
4          2d3a3417_name      TH_Chakra_Petch

In [ ]:
origin_submit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383988 entries, 0 to 383987
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   Id         383988 non-null  object
 1   Predicted  12 non-null      object
dtypes: object(2)
memory usage: 5.9+ MB


In [ ]:
predicted_csv = pd.read_csv("/content/sample_submission.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
def decodePredict(num):
  if(int(num) == 0): return "Angsana_New"
  if(int(num) == 1): return "Cordia_New"
  if(int(num) == 2): return "DM_Shining_Star_Regular"
  if(int(num) == 3): return "FC_Knomphing_Regular"
  if(int(num) == 4): return "fonttintin"
  if(int(num) == 5): return "Kunlasatri"
  if(int(num) == 6): return "TH_Chakra_Petch"
  if(int(num) == 7): return "TH_Charm_of_AU"
  if(int(num) == 8): return "TH_Mali_Grade6"
  if(int(num) == 9): return "TH_Sarabun"
  # 0 Angsana_New
  # 1 Cordia_New
  # 2 DM_Shining_Star_Regular
  # 3 FC_Knomphing_Regular
  # 4 fonttintin
  # 5 Kunlasatri
  # 6 TH_Chakra_Petch
  # 7 TH_Charm_of_AU
  # 8 TH_Mali_Grade6
  # 9 TH_Sarabun

In [ ]:
for i in tqdm(range(len(predicted_csv['parentId']))):
    idx = origin_submit['Id'].loc[lambda x: x==str(predicted_csv[i])+"_name"].index
    # print(idx[0])
    origin_submit['Predicted'][idx[0]] = predicted_csv['prediction']
    origin_submit['Predicted'][idx[0]+1] = str(predicted_csv['prediction'])+".ttf"